"use client";

import { useState } from "react";
import type { ParsedStorySlide } from "@/components/generators/story-slide-card";

interface ParsedOverview {
  objective: string;
  hookAngle: string;
  primaryCta: string;
  postingTime: string;
}

interface DesignBriefExportProps {
  slides: ParsedStorySlide[];
  overview: ParsedOverview;
  stickerStack: string;
  postingSchedule: string;
}

const STICKER_LABEL: Record<string, string> = {
  poll: "Poll",
  quiz: "Quiz",
  question: "Question",
  slider: "Emoji Slider",
  countdown: "Countdown",
  reveal: "Reveal (DM unlock)",
  link: "Link",
  "add-yours": "Add Yours",
  mention: "Mention",
  location: "Location",
  music: "Music",
  none: "No sticker",
};

function buildDesignBrief(
  slides: ParsedStorySlide[],
  overview: ParsedOverview,
  stickerStack: string,
  postingSchedule: string,
): string {
  const lines: string[] = [];

  lines.push("# Instagram Stories — Design Brief");
  lines.push("");
  lines.push(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Overview
  lines.push("## Series Overview");
  lines.push("");
  if (overview.objective)
    lines.push(`- **Objective:** ${overview.objective}`);
  if (overview.hookAngle)
    lines.push(`- **Hook Angle:** ${overview.hookAngle}`);
  if (overview.primaryCta)
    lines.push(`- **Primary CTA:** ${overview.primaryCta}`);
  if (overview.postingTime)
    lines.push(`- **Posting Time:** ${overview.postingTime}`);
  lines.push("");

  // Technical specs
  lines.push("## Technical Specs");
  lines.push("");
  lines.push("- **Resolution:** 1080 x 1920 px (9:16)");
  lines.push("- **Safe Zone:** 1080 x 1610 px (top/bottom 155px reserved for UI)");
  lines.push("- **Edge Margins:** Min 65px from edges");
  lines.push("- **Min Font Size:** 24px (bold/semi-bold + 2pt stroke or shadow)");
  lines.push("- **Design for:** Silent viewing (every slide must communicate without sound)");
  lines.push("");

  // Per-slide specs
  lines.push("## Slide-by-Slide Specs");
  lines.push("");

  for (const slide of slides) {
    lines.push(`### Slide ${slide.index} — ${slide.funnelRole}`);
    lines.push("");
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| **Headline** | ${slide.headline || "—"} |`);
    lines.push(
      `| **Body Text** | ${slide.body && slide.body !== "—" ? slide.body : "—"} |`,
    );
    lines.push(`| **Visual Direction** | ${slide.visualDirection || "—"} |`);
    lines.push(`| **Image Recommendation** | ${slide.imageRecommendation || "—"} |`);
    const stickerLabel =
      STICKER_LABEL[slide.sticker.type.toLowerCase()] ?? slide.sticker.type;
    lines.push(
      `| **Sticker** | ${stickerLabel}${slide.sticker.copy ? ` — "${slide.sticker.copy}"` : ""} |`,
    );
    lines.push(`| **Retention Tactic** | ${slide.retentionTactic || "—"} |`);
    lines.push(`| **Expected Signal** | ${slide.expectedSignal || "—"} |`);
    lines.push("");
  }

  // Sticker stack
  if (stickerStack) {
    lines.push("## Sticker Stack Strategy");
    lines.push("");
    lines.push(stickerStack);
    lines.push("");
  }

  // Posting schedule
  if (postingSchedule) {
    lines.push("## Posting Schedule");
    lines.push("");
    lines.push(postingSchedule);
    lines.push("");
  }

  // Color palette reference
  lines.push("## Suggested Color Palette");
  lines.push("");
  lines.push("Adapt these gradients to match your brand colors:");
  lines.push("");
  lines.push("| Slide | Suggested Background |");
  lines.push("|-------|---------------------|");
  const palette = [
    "#833AB4 → #E1306C → #F77737",
    "#0F2027 → #203A43 → #2C5364",
    "#FF6A00 → #EE0979",
    "#1F1C2C → #928DAB",
    "#0F0C29 → #302B63 → #24243E",
    "#134E5E → #71B280",
    "#7F00FF → #E100FF",
    "#283048 → #859398",
    "#FF512F → #DD2476",
    "#36D1DC → #5B86E5",
    "#000428 → #004E92",
    "#3A1C71 → #D76D77 → #FFAF7B",
    "#0B486B → #F56217",
  ];
  for (let i = 0; i < slides.length; i++) {
    lines.push(`| Slide ${slides[i].index} | ${palette[i % palette.length]} |`);
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("*Generated by CopyKing Instagram Stories Generator*");

  return lines.join("\n");
}

export function DesignBriefExport({
  slides,
  overview,
  stickerStack,
  postingSchedule,
}: DesignBriefExportProps) {
  const [copied, setCopied] = useState(false);

  if (slides.length === 0) return null;

  const brief = buildDesignBrief(slides, overview, stickerStack, postingSchedule);

  const handleDownload = () => {
    const blob = new Blob([brief], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `stories-design-brief-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(brief);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3">
      <p className="text-xs text-text-tertiary">
        Download a complete design brief with per-slide specs, visual direction,
        sticker configs, and technical requirements — ready to hand off to a
        designer or use with Canva/Figma.
      </p>

      <div className="flex gap-2">
        <button
          onClick={handleDownload}
          className="ck-btn-primary px-4 py-2 rounded-lg text-sm font-medium inline-flex items-center gap-2"
        >
          <svg
            className="w-4 h-4"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"
            />
          </svg>
          Download .md
        </button>

        <button
          onClick={handleCopy}
          className="ck-btn-secondary px-4 py-2 rounded-lg text-sm font-medium inline-flex items-center gap-2"
        >
          {copied ? (
            <>
              <svg
                className="w-4 h-4"
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M4.5 12.75l6 6 9-13.5"
                />
              </svg>
              Copied
            </>
          ) : (
            <>
              <svg
                className="w-4 h-4"
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184"
                />
              </svg>
              Copy to clipboard
            </>
          )}
        </button>
      </div>

      {/* Preview */}
      <details className="group">
        <summary className="cursor-pointer text-[11px] font-medium text-text-tertiary hover:text-text-secondary flex items-center gap-1.5 select-none">
          <svg
            className="w-3 h-3 transition-transform group-open:rotate-90"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M8.25 4.5l7.5 7.5-7.5 7.5"
            />
          </svg>
          Preview brief content
        </summary>
        <div className="mt-2 max-h-64 overflow-y-auto rounded-lg bg-background border border-border p-3 text-[11px] font-mono text-text-secondary whitespace-pre-wrap">
          {brief}
        </div>
      </details>
    </div>
  );
}
